## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
required = []

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
ignored = [
	"github.com/timtadh/dynagrok/examples/",
	"github.com/timtadh/dynagrok/examples/src/",
	"github.com/timtadh/dynagrok/examples/src/github.com",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto",
	"github.com/timtadh/dynagrok/examples/src/github.com/shurcooL",
	"github.com/timtadh/dynagrok/examples/src/github.com/shurcooL/sanitized_anchor_name",
	"github.com/timtadh/dynagrok/examples/src/github.com/russross",
	"github.com/timtadh/dynagrok/examples/src/github.com/russross/blackfriday",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc/bluemonday",
	"github.com/timtadh/dynagrok/examples/src/dynagrok",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/avl",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/avl/testcases",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/blackfriday",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/fac",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/fib",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/exit",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/dot",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/tester",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/charset",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/charset/testdata",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit/split",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit/scripted",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/main",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/atom",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/linkedlist",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/linkedlist/driver",
	"github.com/timtadh/dynagrok/examples/src/golang.org",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net",
	"github.com/timtadh/dynagrok/examples/src/gopkg.in",
	"github.com/timtadh/dynagrok/examples/src/gopkg.in/sourcemap.v1",
]

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
[[constraint]]
## Required: the root import path of the project being constrained.
name = "github.com/timtadh/dynagrok"

## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "0.5.0"
branch = "master"
# revision = "abc123"

## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"
