## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
required = []

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
ignored = [
	"github.com/timtadh/dynagrok/examples/",
	"github.com/timtadh/dynagrok/examples/src/",
	"github.com/timtadh/dynagrok/examples/src/github.com",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos/src",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos/src/github.com",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos/src/github.com/timtadh",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/combos/src/github.com/timtadh/lexmachine",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src/github.com",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src/github.com/timtadh",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src/github.com/timtadh/combos",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src/github.com/timtadh/lexmachine",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/dot/src/github.com/timtadh/data-structures",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/queue",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/frontend",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/inst",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/lexc",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/machines",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/src",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/src/github.com",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/src/github.com/timtadh",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/src/github.com/timtadh/getopt",
	"github.com/timtadh/dynagrok/examples/src/github.com/timtadh/lexmachine/src/github.com/timtadh/data-structures",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/dbg",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/otto",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/terst",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/repl",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/ast",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/underscore",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/file",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/registry",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/test",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/test/testcases",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/test/testcases/otto",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/test/testcases/otto/m1",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/parser",
	"github.com/timtadh/dynagrok/examples/src/github.com/robertkrimen/otto/token",
	"github.com/timtadh/dynagrok/examples/src/github.com/shurcooL",
	"github.com/timtadh/dynagrok/examples/src/github.com/shurcooL/sanitized_anchor_name",
	"github.com/timtadh/dynagrok/examples/src/github.com/russross",
	"github.com/timtadh/dynagrok/examples/src/github.com/russross/blackfriday",
	"github.com/timtadh/dynagrok/examples/src/github.com/russross/blackfriday/testdata",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc/bluemonday",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc/bluemonday/cmd",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc/bluemonday/cmd/sanitise_html_email",
	"github.com/timtadh/dynagrok/examples/src/github.com/microcosm-cc/bluemonday/cmd/sanitise_ugc",
	"github.com/timtadh/dynagrok/examples/src/dynagrok",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/avl",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/avl/testcases",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/blackfriday",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/fac",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/fib",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/exit",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/dot",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/tester",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/charset",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/charset/testdata",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit/split",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/testdata/webkit/scripted",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/main",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/html/atom",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/linkedlist",
	"github.com/timtadh/dynagrok/examples/src/dynagrok/examples/linkedlist/driver",
	"github.com/timtadh/dynagrok/examples/src/golang.org",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/proxy",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/idna",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/icmp",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/websocket",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/context",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/context/ctxhttp",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/ipv6",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/publicsuffix",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/bpf",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/bpf/testdata",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/xsrftoken",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/trace",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/dns",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/dns/dnsmessage",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/http2",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/http2/hpack",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/http2/testdata",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/http2/h2demo",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/http2/h2i",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/route",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/lex",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/lex/httplex",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/lif",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/internal",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/internal/iana",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/internal/timeseries",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/internal/netreflect",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/internal/nettest",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/ipv4",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/netutil",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/webdav",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/webdav/internal",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/webdav/internal/xml",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/dict",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/charset",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/charset/testdata",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/testdata",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/testdata/webkit",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/testdata/webkit/scripted",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/html/atom",
	"github.com/timtadh/dynagrok/examples/src/golang.org/x/net/nettest",
	"github.com/timtadh/dynagrok/examples/src/gopkg.in",
	"github.com/timtadh/dynagrok/examples/src/gopkg.in/sourcemap.v1",
	"github.com/timtadh/dynagrok/examples/src/gopkg.in/sourcemap.v1/base64vlq",
]
[[constraint]]
name = "github.com/timtadh/getopt"
version = "^1.0.0"

[[constraint]]
name = "github.com/timtadh/data-structures"
version = "^0.5.0"

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
## [[constraint]]
## Required: the root import path of the project being constrained.
## name = "github.com/timtadh/dynagrok"
## 
## ## Recommended: the version constraint to enforce for the project.
## ## Only one of "branch", "version" or "revision" can be specified.
## # version = "0.5.0"
## branch = "master"
## # revision = "abc123"
## 
## ## Optional: an alternate location (URL or import path) for the project's source.
## # source = "https://github.com/myfork/package.git"
